### ISSUE TITLE
json: cannot unmarshal object into Go struct field SignInResponse.pastSubscriptions of type string

### ISSUE THREAD

**Issue by wichtfx** [jrudio/go-plex-client#45]
Yet another unmarshal error... It seems that we also need a custom unmarshaller to convert a single element into an array. Or is there something I'm unaware of in this case?

It might be difficult to reproduce the issue as your json is most likely different than mine. I simply did `./main signin username password`

**Comment by jrudio** [comment]
I think pastSubscriptions relates to plex pass, please correct me if I am wrong. 

So the commit 76aabd29f85479a0c8b47fa8877e0cbc1a43afc4 was tested using an account with just one lifetime plex pass and another account that has never had a plex pass, so I wasn't able to get the json of an account with a filled in pastSubscription and defaulted to using a []string. 

Assuming you ran into this issue because you have an account that populates pastSubscription, are you able to assist on this? It would be much appreciated!
